@local=http://localhost:3900/Api 
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NmVhYWQ1ZTNhYjE4MmE3OTBiMjVjNTEiLCJiaXoiOnRydWUsImlhdCI6MTcyNjY1NjM5NX0.GcOr1XfMg1_sUFXWm1ARfAaw0lowJgGNhvJQZ9wrLeY

###
POST {{local}}/users
Content-Type: application/json

{
    "name":"neveen",
    "email":"neveen@gmail.com",
    "password":"Aa123456789",
    "biz":true
}

### Authenticate
POST {{local}}/auth 
Content-Type: application/json

{
    "email":"neveen@gmail.com",
    "password":"Aa123456789"
}

#### Athurization
GET {{local}}/api/users/me
x-auth-token: {{token}}


### Create Card
POST {{local}}/api/cards
x-auth-token: {{token}}
Content-Type: application/json

{
    "bizName": "Lemon",
    "bizDescription": "lemon lemon", 
    "bizAddress": "lemon av.",
    "bizPhone": "0554548444",
    "bizImage": "https://media.istockphoto.com/id/1389128157/photo/lemon-fruit-with-leaf-isolated-whole-lemon-and-a-half-with-leaves-on-white-background-lemons.jpg?s=612x612&w=is&k=20&c=jrEotJaieJfvntSQH2Hq_yAVd_lVjHC1sfuThLrqr0Q="
}